# Website settings
baseurl: "/"
url: "https://www.fundamentals-of-devops.com"
thumbnail_path: "book-3d-cover-no-shadow-medium.png"

# About settings
name: "Fundamentals of DevOps and Software Delivery"
description: "This book is a hands-on guide to software delivery—that is, all the processes, tools, and techniques that are required to run and maintain software in production on an ongoing basis—and DevOps, one of the methodologies used today to make software delivery vastly more efficient."
website_repo_url: "https://github.com/brikis98/fundamentals-of-devops-website"
early_release_url: "#" # TODO: update

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/brikis98"
    label: "Twitter"
    icon: "twitter-square"
    username: "@brikis98"
  linkedin:
    url: "https://www.linkedin.com/in/jbrikman"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/brikis98"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/+YevgeniyBrikman/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "https://www.slideshare.net/brikis98"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/brikis98/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jim@ybrikman.com"
    label: "Email"
    value: "jim@ybrikman.com"
    icon: "envelope-square"

# Jekyll build settings
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
